package uz.script.wincrm.utils;

public enum Resource {
    USER,
    ROLE,
    CLIENT,
    CLIENT_GROUP,
    SUPPLIER,
    UNIT_TYPE,
    GOODS_GROUP,
    GOODS,
    WAREHOUSE,
    WAREHOUSE_ORDER,
    WAREHOUSE_ORDER_ITEM,
    SALE_ORDER,
    SALE_ORDER_ITEM,
    PAYMENT_TYPE,
    PAYMENT,
    STOCK,
    STOCK_HISTORIES,
    EXPENSE,
    EXPENSE_CATEGORY,
    COMPANY_DETAIL,
    DEBT_NOTIFICATION,
    DASHBOARD,
    BOT_SETTINGS
}
